### PR TITLE
Fix mixins, stringifiers, and static attributes

### LINKED ISSUE #49: Rework mixins
The spec [says](https://heycam.github.io/webidl/#es-implements-statements):

> For operations, where the property is a data property with a **Function** object value, each copy of the property must have distinct **Function** objects.

We are not doing that.

### LINKED ISSUE #67: mixin does not properly mix in toString
This currently impacts HTMLAnchorElement. The stringifier from HTMLHyperlinkElementUtils isn't properly mixed into it.

### PR DESCRIPTION
**Pull request by TimothyGu**
This requires a change in jsdom to move idlUtils.mixin to jsdom, as it will no longer be needed or included in webidl2js. I could keep it in webidl2js for the time being however, until the next major bump.

Note, this does not yet fix https://github.com/jsdom/webidl2js/issues/55

Fixes #49.
Fixes #67.

### CODE REVIEW

File: lib/constructs/interface.js [hunk 1]
```diff
@@ -185,7 +221,7 @@ class Interface {
         definingInterface = member[1];
         continue;
       }
-      if (forbiddenMembers.has(member.name)) {
+      if (forbiddenMembers.has(member.name) || member.name && member.name[0] === "_") {
```
Comment (domenic) [inline lib/constructs/interface.js]: It's worth adding a check that our IDL parsing library properly strips the `_`s from source files before handing them to us. I.e., `attribute boolean _foo` should not trigger an error.

File: test/cases/Static.idl [hunk 2]
```diff
@@ -0,0 +1,6 @@
+interface Static {
+  static attribute DOMString abc;
```
Comment (domenic) [inline test/cases/Static.idl]: Nit: I find the alignment here distracting and would prefer no extra spacing.

File: test/__snapshots__/test.js.snap [hunk 3]
```diff
@@ -355,6 +355,357 @@ const Impl = require(\\"../implementations/LegacyArrayClass.js\\");
 "
 `;
 
+exports[`MixedIn.idl 1`] = `
```
Comment (domenic) [inline test/__snapshots__/test.js.snap]: I guess this doesn't directly test that mixing something in to multiple places doesn't reuse the same object... but it does indirectly, as it'd be hard to imagine code generation for the second class that duplicates it.

File: lib/constructs/interface.js [hunk 4]
```diff
@@ -179,16 +231,16 @@ class Interface {
...
+    memberInherited = false;
     for (const member of this.inheritedMembers()) {
-      if (member[0] === inherited) {
-        definingInterface = member[1];
+      if (member === inherited) {
+        memberInherited = true;
         continue;
       }
-      if (forbiddenMembers.has(member.name)) {
+      if (forbiddenMembers.has(member.name) || member.name && member.name[0] === "_") {
```
Comment (Sebmaster) [inline lib/constructs/interface.js]: Parens this && to reduce (my) confusion about operator precedence.

File: lib/constructs/interface.js [hunk 5]
```diff
@@ -208,6 +260,23 @@ class Interface {
...
+    const iface = this.ctx.interfaces.get(source);
+    if (!iface) {
+      if (this.ctx.options.suppressErrors) {
+        return;
+      }
+      throw new Error(`${source} interface not found (used as a mixin for ${this.name})`);
+    }
+
+    // TODO: are these actually allowed by the spec?
+    if (!this.ctx.options.suppressErrors) {
```
Comment (Sebmaster) [inline lib/constructs/interface.js]: Remove this conditional. `suppressErrors` should only be used for stuff we know doesn't work but we know is "safe" to ignore.

**Comment by TimothyGu** [comment]
@domenic 

Comments addressed.

> What does "Refactor Overloads operation collection" accomplish? 

It's pure refactoring so that it is closer to the spec's language. No new features added or bugs fixed.

----

@Sebmaster

Comments addressed.

> Do we really have to use this sentinel in the inherited member call? Can we just split this up into two "iterators"?

No, and done.

File: lib/constructs/interface.js [hunk 6]
```diff
@@ -163,9 +122,98 @@ class Interface {
...
+    for (const member of this.members(seen)) {
+      let key;
+      switch (member.type) {
+        case "operation":
+          key = member.static ? "staticOperations" : "operations";
+          if (member.name) {
+            if (!this[key].has(member.name)) {
+              this[key].set(member.name, new Operation(this.ctx, this, member));
+            } else {
+              this[key].get(member.name).idls.push(member);
```
Comment (Sebmaster) [inline lib/constructs/interface.js]: Is the order of these guaranteed? We're sometimes accessing idls[0]. How do we know that that's the correct one? What's in the others?

Comment (TimothyGu) [reply lib/constructs/interface.js]: The order is not guaranteed. Here are the specific cases in which `idls[0]` is accessed:

- `utils.isOnInstance(this.idls[0], this.interface.idl)`

   This checks for `[Unforgeable]` extended attribute on `this.idls[0]` and returns true if that is the case. The Web IDL [forbids](https://heycam.github.io/webidl/#Unforgeable) some overloads of an operation having that extended attribute and others of the same operation do not:

   > If it does appear on an operation, then it must appear on all operations with the same identifier on that interface.

   We do not enforce this requirement at this moment, and a TODO is included:

   https://github.com/jsdom/webidl2js/blob/398c67c78193068bd018c19daa271b4c4c073adc/lib/constructs/operation.js#L28

   But assuming the input IDL is well-formed, checking the first overload only should suffice.

- `this.idls[0].name || this.name`

   This is a somewhat hacky way of supporting named stringifiers. Basically in case of

   ```webidl
   stringifier DOMString opName();
               DOMString opName(DOMString input);
   ```

   we create two `Operation`s:

   1. one with `op.name` being `"opName"`, but `op.idls` having both overloads, and
   2. the other's `op.name` property manually overridden with `"toString"`, but `op.idls[0]` is still `"opName"`, and `op.idls.length` is always 1.

   For the first case, since all overloads have the same name, choosing which one doesn't matter. For the second case, since there is always going to be one overload, the first and only one it is.

   OTOH, for a more basic case of 

   ```webidl
   stringifier;
   ```

   we know there is only always going to be one overload.

- `this.idls[0].stringifier`

   See above. This can be true only if there is one item in `this.idls`.

I can add some comments and asserts in the code regarding the last two items if that makes it a bit clearer?

Comment (Sebmaster) [reply lib/constructs/interface.js]: I'm fine with a single comment explaining this here (or at the access points, whatever seems clearer).

**Comment by TimothyGu** [comment]
Just a note when publishing a new version: this is a breaking change as it removes `mixin()` from the utils file.

**Comment by domenic** [comment]
I've decided that this is not a breaking change because `mixin()` is undocumented. I think that is the right policy going forward. But, it ended up being done as part of v8.0.0 regardless, so we're safe even if some people don't agree.

In practice, what this means is that fixing #56 and #52 are IMO not breaking changes since they change undocumented APIs and don't change how you write an impl class.

On the other hand I counted #72 as breaking since it changes how you would write an impl class.
