### PR TITLE
Ensure promise-typed operations and attributes return promises

### LINKED ISSUE #79: Promise-returning operations should return Promise.reject on invalid argument
If an interface defines a Promise-returning operation with required arguments, the generated wrapper throws TypeError if insufficient number of arguments are provided. I believe the expected behavior is to return a Promise.reject that throws.

E.g.

```webidl
interface Foo {
  Promise<string> greet(string name);
};
```

Generates:

```js
Foo.prototype.greet = function greet(name) {
  ...
  if (arguments.length < 1) {
    throw new TypeError(
      "Failed to execute 'greet' on 'Foo': " + "1 argument required, but only " + arguments.length + " present."
    );  // [*]
  }

  ...
}
```

[*] should be:

```js
return Promise.reject(new TypeError("<error message>"));
```

I couldn't find exact wording in WebIDL spec about this. However, the return-rejected-promise behavior is what Web Platform Test's idlharness.js enforces.

### PR DESCRIPTION
**Pull request by domenic**
Closes #79.

This removes support for overloading promise operations and non-promise operations, since that would require a more ambitious approach and doesn't seem to appear on the web.

---

Thoughts welcome. The strategy of using `async` for operations and try/catch for attributes makes the output nice but the webidl2js code a bit icky. Threading the async bit through all the operation stuff adds a bit of complexity. And, we might want to abandon that if we _do_ want to support overloads of promise-returning operations vs. non-promise returning ones, since doing that would require an appropriately-scoped try/catch.

### CODE REVIEW

**Comment by domenic** [comment]
I found https://github.com/heycam/webidl/pull/776 which indicates we don't need to worry about supporting overloads between promise-returning and non-promise-returning operations.

File: lib/constructs/attribute.js [hunk 1]
```diff
@@ -23,6 +23,10 @@ class Attribute {
 
     const onInstance = utils.isOnInstance(this.idl, this.interface.idl);
 
+    const async = this.idl.idlType.generic === "Promise";
+    const promiseHandlingBefore = async ? `try {` : ``;
+    const promiseHandlingAfter = async ? `} catch (e) { return Promise.reject(e); }` : ``;
```
Comment (ExE-Boss) [inline lib/constructs/attribute.js:28]:
```suggestion
    const isAsync = this.idl.idlType.generic === "Promise";
    const promiseHandlingBefore = isAsync ? `try {` : ``;
    const promiseHandlingAfter = isAsync ? `} catch (e) { return Promise.reject(e); }` : ``;
```

File: lib/constructs/attribute.js [hunk 2]
```diff
@@ -64,12 +68,18 @@ class Attribute {
...
+      ${promiseHandlingBefore}
       const esValue = this !== null && this !== undefined ? this : globalObject;
       ${brandCheck}
       ${getterBody}
-    `, "get", { configurable });
+      ${promiseHandlingAfter}
+    `, { type: "get" }, { configurable });
 
     if (!this.idl.readonly) {
+      if (async) {
```
Comment (ExE-Boss) [inline lib/constructs/attribute.js:79]:
```suggestion
      if (isAsync) {
```

File: lib/constructs/interface.js [hunk 3]
```diff
@@ -123,7 +123,7 @@ class Interface {
 
   // whence is either "instance" or "prototype"
   // type is either "regular", "get", or "set"
-  addMethod(whence, propName, args, body, type = "regular", {
+  addMethod(whence, propName, args, body, { type = "regular", async = false } = {}, {
```
Comment (ExE-Boss) [inline lib/constructs/interface.js:126]:
```suggestion
  addMethod(whence, propName, args, body, { type = "regular", isAsync = false } = {}, {
```

File: lib/constructs/interface.js [hunk 4]
```diff
@@ -150,11 +150,11 @@ class Interface {
     }
 
     const descriptor = { configurable, enumerable, writable };
-    this._outputMethods.set(propName, { whence, type, args, body, descriptor });
+    this._outputMethods.set(propName, { whence, type, args, body, descriptor, async });
```
Comment (ExE-Boss) [inline lib/constructs/interface.js:153]:
```suggestion
    this._outputMethods.set(propName, { whence, type, args, body, descriptor, isAsync });
```

File: lib/constructs/interface.js [hunk 5]
```diff
@@ -150,11 +150,11 @@ class Interface {
...
   }
 
   // type is either "regular", "get", or "set"
-  addStaticMethod(propName, args, body, type = "regular", {
+  addStaticMethod(propName, args, body, { type = "regular", async = false } = {}, {
```
Comment (ExE-Boss) [inline lib/constructs/interface.js:157]:
```suggestion
  addStaticMethod(propName, args, body, { type = "regular", isAsync = false } = {}, {
```

File: lib/constructs/interface.js [hunk 6]
```diff
@@ -178,7 +178,7 @@ class Interface {
     }
 
     const descriptor = { configurable, enumerable, writable };
-    this._outputStaticMethods.set(propName, { type, args, body, descriptor });
+    this._outputStaticMethods.set(propName, { type, args, body, descriptor, async });
```
Comment (ExE-Boss) [inline lib/constructs/interface.js:181]:
```suggestion
    this._outputStaticMethods.set(propName, { type, args, body, descriptor, isAsync });
```

File: lib/constructs/interface.js [hunk 7]
```diff
@@ -1311,40 +1311,40 @@ class Interface {
...
-    const addOne = (name, args, body) => {
+    const addOne = (name, args, body, { isAsync, isStatic }) => {
       this.str += `
-        ${name}(${formatArgs(args)}) {${body}}
+        ${isStatic ? "static " : ""}${isAsync ? "async " : ""}${name}(${formatArgs(args)}) {${body}}
       `;
     };
 
-    for (const [name, { whence, type, args, body }] of this._outputMethods) {
+    for (const [name, { whence, type, args, body, async }] of this._outputMethods) {
```
Comment (ExE-Boss) [inline lib/constructs/interface.js:1320]:
```suggestion
    for (const [name, { whence, type, args, body, isAsync }] of this._outputMethods) {
```

File: lib/constructs/interface.js [hunk 8]
```diff
@@ -1311,40 +1311,40 @@ class Interface {
...
       if (whence !== "prototype") {
         continue;
       }
 
       const propName = utils.stringifyPropertyKey(name);
       if (type === "regular") {
-        addOne(propName, args, body);
+        addOne(propName, args, body, { isAsync: async });
```
Comment (ExE-Boss) [inline lib/constructs/interface.js:1327]:
```suggestion
        addOne(propName, args, body, { isAsync });
```

File: lib/constructs/interface.js [hunk 9]
```diff
@@ -1311,40 +1311,40 @@ class Interface {
...
       } else {
         if (body[0] !== undefined) {
-          addOne(`get ${propName}`, [], body[0]);
+          addOne(`get ${propName}`, [], body[0], { isAsync: async });
```
Comment (ExE-Boss) [inline lib/constructs/interface.js:1330]:
```suggestion
          addOne(`get ${propName}`, [], body[0], { isAsync });
```

File: lib/constructs/interface.js [hunk 10]
```diff
@@ -1311,40 +1311,40 @@ class Interface {
...
         }
         if (body[1] !== undefined) {
-          addOne(`set ${propName}`, args, body[1]);
+          addOne(`set ${propName}`, args, body[1], { isAsync: async });
```
Comment (ExE-Boss) [inline lib/constructs/interface.js:1333]:
```suggestion
          addOne(`set ${propName}`, args, body[1], { isAsync });
```

File: lib/constructs/interface.js [hunk 11]
```diff
@@ -1311,40 +1311,40 @@ class Interface {
...
         }
       }
     }
 
-    for (const [name, { type, args, body }] of this._outputStaticMethods) {
+    for (const [name, { type, args, body, async }] of this._outputStaticMethods) {
```
Comment (ExE-Boss) [inline lib/constructs/interface.js:1338]:
```suggestion
    for (const [name, { type, args, body, isAsync }] of this._outputStaticMethods) {
```

File: lib/constructs/interface.js [hunk 12]
```diff
@@ -1311,40 +1311,40 @@ class Interface {
...
       const propName = utils.stringifyPropertyKey(name);
       if (type === "regular") {
-        addOne(`static ${propName}`, args, body);
+        addOne(`${propName}`, args, body, { isAsync: async, isStatic: true });
```
Comment (ExE-Boss) [inline lib/constructs/interface.js:1341]:
```suggestion
        addOne(`${propName}`, args, body, { isAsync, isStatic: true });
```

File: lib/constructs/interface.js [hunk 13]
```diff
@@ -1311,40 +1311,40 @@ class Interface {
...
       } else {
         if (body[0] !== undefined) {
-          addOne(`static get ${propName}`, [], body[0]);
+          addOne(`get ${propName}`, [], body[0], { isAsync: async, isStatic: true });
```
Comment (ExE-Boss) [inline lib/constructs/interface.js:1344]:
```suggestion
          addOne(`get ${propName}`, [], body[0], { isAsync, isStatic: true });
```

File: lib/constructs/interface.js [hunk 14]
```diff
@@ -1311,40 +1311,40 @@ class Interface {
...
         }
         if (body[1] !== undefined) {
-          addOne(`static set ${propName}`, args, body[0]);
+          addOne(`set ${propName}`, args, body[0], { isAsync: async, isStatic: true });
```
Comment (ExE-Boss) [inline lib/constructs/interface.js:1347]:
```suggestion
          addOne(`set ${propName}`, args, body[0], { isAsync, isStatic: true });
```

File: lib/constructs/interface.js [hunk 15]
```diff
@@ -1311,40 +1311,40 @@ class Interface {
   }
 
   generateOffInstanceMethods() {
-    const addOne = (name, args, body) => {
+    const addOne = (name, args, body, { isAsync, isStatic }) => {
```
Comment (ExE-Boss) [inline lib/constructs/interface.js:1314]:
```suggestion
    const addOne = (name, args, body, { isAsync = false, isStatic = false }) => {
```

File: lib/constructs/operation.js [hunk 16]
```diff
@@ -48,6 +62,7 @@ class Operation {
     }
 
     const onInstance = this.isOnInstance();
+    const async = this.isAsync();
```
Comment (ExE-Boss) [inline lib/constructs/operation.js:65]:
```suggestion
    const isAsync = this.isAsync();
```

File: lib/constructs/operation.js [hunk 17]
```diff
@@ -99,15 +114,15 @@ class Operation {
     str += invocation;
 
     if (this.static) {
-      this.interface.addStaticMethod(this.name, argNames, str);
+      this.interface.addStaticMethod(this.name, argNames, str, { async });
```
Comment (ExE-Boss) [inline lib/constructs/operation.js:117]:
```suggestion
      this.interface.addStaticMethod(this.name, argNames, str, { isAsync });
```

File: lib/constructs/operation.js [hunk 18]
```diff
@@ -99,15 +114,15 @@ class Operation {
...
     } else {
       const forgeable = !utils.getExtAttr(this.idls[0].extAttrs, "Unforgeable");
       this.interface.addMethod(
         onInstance ? "instance" : "prototype",
         this.name,
         argNames,
         str,
-        "regular",
+        { type: "regular", async },
```
Comment (ExE-Boss) [inline lib/constructs/operation.js:125]:
```suggestion
        { type: "regular", isAsync },
```

File: test/__snapshots__/test.js.snap [hunk 19]
```diff
@@ -2983,12 +3023,55 @@ exports.install = (globalObject, globalNames) => {
...
       return esValue[implSymbol].promiseConsumer(...args);
     }
+
+    async promiseOperation() {
+      const esValue = this !== null && this !== undefined ? this : globalObject;
+      if (!exports.is(esValue)) {
+        throw new TypeError(\\"Illegal invocation\\");
+      }
+
+      return utils.tryWrapperForImpl(esValue[implSymbol].promiseOperation());
```
Comment (ExE-Boss) [inline test/__snapshots__/test.js.snap:3033]: This has to generate:
```js
       return utils.tryWrapperForImpl(await esValue[implSymbol].promiseOperation());
```

File: test/__snapshots__/test.js.snap [hunk 20]
```diff
@@ -2983,12 +3023,55 @@ exports.install = (globalObject, globalNames) => {
...
+
+    get promiseAttribute() {
+      try {
+        const esValue = this !== null && this !== undefined ? this : globalObject;
+
+        if (!exports.is(esValue)) {
+          throw new TypeError(\\"Illegal invocation\\");
+        }
+
+        return utils.tryWrapperForImpl(esValue[implSymbol][\\"promiseAttribute\\"]);
```
Comment (ExE-Boss) [inline test/__snapshots__/test.js.snap:3044]: This has to generate:
```js
          return Promise.resolve(esValue[implSymbol]["promiseAttribute"])
            .then(utils.tryWrapperForImpl);
```

File: test/__snapshots__/test.js.snap [hunk 21]
```diff
@@ -2983,12 +3023,55 @@ exports.install = (globalObject, globalNames) => {
...
+      } catch (e) {
+        return Promise.reject(e);
+      }
+    }
+
+    static async staticPromiseOperation() {
+      return utils.tryWrapperForImpl(Impl.implementation.staticPromiseOperation());
```
Comment (ExE-Boss) [inline test/__snapshots__/test.js.snap:3051]: This has to generate:
```js
       return utils.tryWrapperForImpl(await Impl.implementation.staticPromiseOperation());
```

File: test/__snapshots__/test.js.snap [hunk 22]
```diff
@@ -2983,12 +3023,55 @@ exports.install = (globalObject, globalNames) => {
...
+    }
+
+    static get staticPromiseAttribute() {
+      try {
+        const esValue = this !== null && this !== undefined ? this : globalObject;
+
+        return Impl.implementation[\\"staticPromiseAttribute\\"];
```
Comment (ExE-Boss) [inline test/__snapshots__/test.js.snap:3058]: This has to generate:
```js
          return Promise.resolve(Impl.implementation["staticPromiseAttribute"])
            .then(utils.tryWrapperForImpl);
```

**Comment by domenic** [comment]
Please do not review pull requests that your review was not requested on. It is very rude to come into someone else's project and critique their code unsolicited.

File: test/__snapshots__/test.js.snap (hunk 19 above)
Comment (domenic) [reply test/__snapshots__/test.js.snap:3033]: This and your other unsolicited comments are not so straightforward.

You are suggesting that we incorporate the unwrapping done in https://github.com/jsdom/webidl2js/pull/108 here. However, that breaks the ability for the impl method/getter to return the same promise multiple times. That is especially problematic for attributes, where `x.attr === x.attr` is almost always what the spec intends.

I think we should leave working on the unwrapping to https://github.com/jsdom/webidl2js/pull/108 or some continuation of that has better discussion behind it.

File: lib/constructs/operation.js [hunk 23]
```diff
@@ -25,6 +25,20 @@ class Operation {
     return firstOverloadOnInstance;
   }
 
+  isAsync() {
+    const firstAsync = this.idls[0].idlType.generic === "Promise";
```
Comment (TimothyGu) [inline lib/constructs/operation.js:29]: Linking to https://github.com/heycam/webidl/pull/776 would be useful.

File: lib/constructs/interface.js [hunk 24]
```diff
@@ -1311,40 +1311,40 @@ class Interface {
...
       this.str += `
-        ${name}(${formatArgs(args)}) {${body}}
+        ${isStatic ? "static " : ""}${isAsync ? "async " : ""}${name}(${formatArgs(args)}) {${body}}
```
Comment (TimothyGu) [inline lib/constructs/interface.js:1316]: Do we actually need the function to be async? I don't see `await` being used anywhere, and I fear that this difference could in fact be observable by the number of ticks it passed before the promise is rejected with a synchronously thrown error.

Comment (ExE-Boss) [reply lib/constructs/interface.js:1316]: I talk about that in <https://github.com/jsdom/webidl2js/issues/79#issuecomment-617738500>.

Comment (domenic) [reply lib/constructs/interface.js:1316]: It's a convenient way to convert exceptions into rejections. But, it sounds like folks are in favor of instead wrapping everything in try/catch, so I'll do that.

File: test/cases/PromiseTypes.webidl [hunk 25]
```diff
@@ -2,4 +2,13 @@
 interface PromiseTypes {
   void voidPromiseConsumer(Promise<void> p);
   void promiseConsumer(Promise<double> p);
+
+  Promise<void> promiseOperation();
+  readonly attribute Promise<void> promiseAttribute;
+
+  [Unforgeable] Promise<void> unforgeablePromiseOperation();
+  [Unforgeable] readonly attribute Promise<void> unforgeablePromiseAttribute;
```
Comment (TimothyGu) [inline test/cases/PromiseTypes.webidl:10]:
```suggestion
  [LegacyUnforgeable] Promise<void> unforgeablePromiseOperation();
  [LegacyUnforgeable] readonly attribute Promise<void> unforgeablePromiseAttribute;
```
